token: "NDgxOTAxMjUyMDA3OTUyMzg1.Dl90_Q.EJF_8l2Yh1WW9vJ2lDUrvgXnRF8"
client-id: "481901252007952385"
website-url: "http://127.0.0.1:6660"
frontend-folder: "C:\\Users\\Whistler\\Documents\\IdeaProjects\\PerfectDreams\\Gabriela\\frontend"